version: "3"

services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fixbus_db_hibernate
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1527956Makc"
    ports:
      - 8080:8080

  db:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=1527956Makc
      - MYSQL_DATABASE=fixbus_db_hibernate
    ports:
      - 3307:3306

volumes:
  mysql-data:
  grafana-data: